"use client";

import "./globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
// import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ height: "100%" }}>
        <Navbar />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
